# Generated by Django 4.0 on 2022-01-14 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_content_contact_time_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13)),
                ('timeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('driveby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.driver')),
            ],
        ),
    ]
