# Generated by Django 4.0.4 on 2022-05-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
    ]
