# Generated by Django 4.0 on 2022-01-14 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
