# Generated by Django 4.0 on 2022-01-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_service_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pincode',
        ),
    ]
