# Generated by Django 4.0.3 on 2022-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_service_completed_service_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
