# Generated by Django 4.0.3 on 2022-05-01 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_technology_alter_service_driveby_alter_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='title_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
